In [7]:
import pandas as pd

In [16]:
df=pd.read_csv('PCOS_final_cleaned.csv')
df.head()

regularity_periods  weight_gain  excess_hair  dark_patches  pimples  \
0                   2            1            1             0        1   
1                   3            1            1             0        0   
2                   2            1            1             0        0   
3                   4            0            1             0        0   
4                   3            1            1             0        0   

   depression_and_anxiety  family_diabetes  mantaining_weight  oilyskin  \
0                       1                0                  1         1   
1                       1                0                  1         0   
2                       1                0                  1         0   
3                       1                1                  1         0   
4                       1                1                  1         1   

   hair_thinning  freq_eat_places  regular_exercise  sleep_time  wake_time  \
0              1                0                 0          11          7   
1              1                0                 0          12          8   
2              1                0                 0          11          7   
3              1                0                 0           3          7   
4              1                0                 0          12          8   

   hostel_stress  personal_problems  peer_pressure  dietrty_habits  \
0              0                  1              0               0   
1              0                  0              0               1   
2              0                  0              1               0   
3              0                  0              0               1   
4              0                  1              0               0   

   fast_foods_freq  PCOS_result  
0                2        False  
1                2         True  
2                2        False  
3                2        False  
4                2         True

In [24]:
df1=df
       

In [25]:
y=df1.PCOS_result.values

In [26]:
y

array([False,  True, False, False,  True, False,  True, False,  True,
        True,  True,  True, False,  True, False, False, False, False,
        True,  True, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False,  True, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False, False, False,  True,  True, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [27]:
del df1["PCOS_result"]

In [28]:
x=df1.values

In [29]:
x

array([[2, 1, 1, ..., 0, 0, 2],
       [3, 1, 1, ..., 0, 1, 2],
       [2, 1, 1, ..., 1, 0, 2],
       ...,
       [1, 0, 0, ..., 0, 0, 2],
       [1, 0, 1, ..., 0, 1, 2],
       [1, 0, 0, ..., 0, 0, 2]], dtype=int64)

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=3)

In [39]:
x_train.shape ,y_train.shape

((95, 19), (95,))

In [40]:
x_test.shape, y_test.shape

((24, 19), (24,))

In [42]:
dt=DecisionTreeClassifier()
clf=dt.fit(x_train,y_train)
clf.score(x_train,y_train),clf.score(x_test,y_test)

(0.9894736842105263, 1.0)

In [43]:
rf = RandomForestClassifier()
clf1=rf.fit(x_train,y_train)
clf1.score(x_train,y_train),clf1.score(x_test,y_test)

(0.9894736842105263, 1.0)

In [44]:
#try stacking, bagging and boosting later on

In [58]:
test1=[3,1,1,0,0,1,0,1,0,1,0,0,12,8,0,0,0,1,2]

In [59]:
import numpy as np
test1 = np.array(test1).reshape(1, len(test1))


In [61]:
clf1.predict(test1)

array([ True])

In [62]:
import pickle

In [64]:
filename = 'PCOS_model.sav'
pickle.dump(clf1, open(filename, 'wb'))

In [65]:
rf.n_estimators

100